[package]
name = "carbon-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-general-category = "0.4"

[build-dependencies]
unicode-general-category = "0.4"
